vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set autoindent")
vim.cmd("set nu");
vim.cmd("set relativenumber")
vim.cmd("set cursorline")

-- disables compatibility with vi
vim.cmd("set nocompatible")
vim.cmd("set ignorecase")
vim.cmd("set cursorline")
vim.cmd("set cursorline")
vim.cmd(":map <Up> <Nop>")
vim.cmd(":map <Down> <Nop>")
vim.cmd(":map <Left> <Nop>")
vim.cmd(":map <Right> <Nop>")
vim.cmd(":imap <Up> <Nop>")
vim.cmd(":imap <Down> <Nop>")
vim.cmd(":imap <Left> <Nop>")
vim.cmd(":imap <Right> <Nop>")
vim.cmd(":vmap <Up> <Nop>")
vim.cmd(":vmap <Down> <Nop>")
vim.cmd(":vmap <Left> <Nop>")
vim.cmd(":vmap <Right> <Nop>")

